ALTER TABLE card
	CHANGE `name` name_fra VARCHAR(100) NOT NULL;
ALTER TABLE card
	ADD COLUMN img_url VARCHAR(100) NOT NULL,
	ADD COLUMN colors VARCHAR(10) NOT NULL,
	ADD COLUMN cost VARCHAR(20) NOT NULL,
	ADD COLUMN `set` VARCHAR(50) NOT NULL,
	ADD COLUMN set_name VARCHAR(50) NOT NULL,
	ADD COLUMN rarity VARCHAR(10) NOT NULL,
	ADD COLUMN last_update DATETIME NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	ADD COLUMN multiverse_id INT NULL UNIQUE,
	ADD COLUMN scryfall_id VARCHAR(100) NULL UNIQUE, -- can be NULL before the v1
	ADD COLUMN name_eng VARCHAR(100) NOT NULL;
